import axios from 'axios';

const TWO_FACTOR_API_KEY = process.env.TWO_FACTOR_API_KEY || 'f46c714b-8d6a-11f1-908b-0200cd936042';

export interface TwoFactorResponse {
  success: boolean;
  details?: string;
  error?: string;
}

/**
 * Sends a 6-digit OTP to an Indian mobile number via 2Factor.in SMS Gateway.
 * @param phone 10-digit Indian mobile number
 * @param otp 6-digit OTP code generated by the server
 */
export const send2FactorOTP = async (phone: string, otp: string): Promise<TwoFactorResponse> => {
  try {
    const apiKey = process.env.TWO_FACTOR_API_KEY || TWO_FACTOR_API_KEY;
    const cleanPhone = phone.trim().slice(-10);

    // 2Factor REST API URL format for custom OTP:
    // GET https://2factor.in/API/V1/{api_key}/SMS/+91{phone_number}/{otp_val}
    const url = `https://2factor.in/API/V1/${apiKey}/SMS/+91${cleanPhone}/${otp}`;

    console.log(`[2Factor SMS Service] Dispatching OTP ${otp} to +91${cleanPhone}...`);

    const response = await axios.get(url, { timeout: 10000 });

    if (response.data && response.data.Status === 'Success') {
      console.log(`[2Factor SMS Success] Session Id / Details: ${response.data.Details}`);
      return {
        success: true,
        details: response.data.Details,
      };
    } else {
      console.error(`[2Factor SMS Error] Status: ${response.data?.Status}, Details: ${response.data?.Details}`);
      return {
        success: false,
        error: response.data?.Details || 'Failed to dispatch SMS via 2Factor gateway',
      };
    }
  } catch (err: any) {
    const errMsg = err.response?.data?.Details || err.response?.data?.message || err.message;
    console.error(`[2Factor SMS Exception] ${errMsg}`);
    return {
      success: false,
      error: errMsg,
    };
  }
};
